name: Deploy AcademyCodeWeb to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F4FF9D89C24F4CB6868B78EE4F973681 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E76548CD8E2A40BDADF6BF74A2930E42 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1B5A0BB8BA3F4A9988AECB9A9953215C }}

      - name: Desplegar en Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AcademyCodeWeb'
          slot-name: 'Production'
          package: .
