name: Deploy AcademyCode to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D9BFC80218D4182961F1D479E612CC0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_ECE97CCECE9F4B3CACE239E1A13FB35F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8F55F7BD45F744EDA44E2810A6185A50 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AcademyCode'
          slot-name: 'Production'
          package: .
